name: root_flow
description: App de bem-estar com foco em energia, fluxo e foco
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  google_fonts: ^6.1.0
  flutter_neumorphic: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  share_plus: ^12.0.2
  font_awesome_flutter: ^11.0.0
  file_picker: ^8.1.4
  url_launcher: ^6.3.1
  package_info_plus: ^9.0.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  # Android 8+ (Adaptive Icon)
  adaptive_icon_background: "#0B2E1D"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

  # iOS
  remove_alpha_ios: false
  
fonts:
  - family: NotoSans
    fonts:
      - asset: assets/fonts/NotoSans-Regular.ttf